### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by snpdzk** [Nyan-Work/xaero-map-addition#5]
### Minecraft Version

1.19.4

### Xaero Map Addition Version

xaero-map-addition-all-0.2.79+91bd337-beta

### Description

启动时崩溃，删除xma后正常启动

### To Reproduce

启动崩溃

### Log
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-09-24 16:52:09
Description: Unexpected error

java.lang.RuntimeException: java.lang.RuntimeException: Mixin transformation of xaero.map.gui.GuiMap failed
	at xaero.map.WorldMap.tryLoadLater(WorldMap.java:262)
	at xaero.map.core.XaeroWorldMapCore.onMinecraftRunTick(XaeroWorldMapCore.java:170)
	at net.minecraft.class_310.handler$igp001$xaeroworldmap$onRunTickStart(class_310.java:35514)
	at net.minecraft.class_310.method_1523(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)
Caused by: java.lang.RuntimeException: Mixin transformation of xaero.map.gui.GuiMap failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at xaero.map.radar.tracker.PlayerTrackerMenuRenderer$Builder.build(PlayerTrackerMenuRenderer.java:116)
	at xaero.map.WorldMap.loadClient(WorldMap.java:162)
	at xaero.map.WorldMap.onInitializeClient(WorldMap.java:77)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 19 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for xaero_map_addition.mixins.json:MixinGuiMap from mod xaero_map_addition-1_19_4 during activity: [Transform -> Method renderHighlightWaypoint(Lnet/minecraft/class_4587;IIFLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> GETSTATIC -> com/plusls/ommc/feature/highlithtWaypoint/HighlightWaypointUtil::highlightPos:Lnet/minecraft/class_2338;]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:313)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: com.plusls.ommc.feature.highlithtWaypoint.HighlightWaypointUtil
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMemberReference(MixinPreProcessorStandard.java:786)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformField(MixinPreProcessorStandard.java:777)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:740)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:307)
	... 28 more
Caused by: java.lang.ClassNotFoundException: com.plusls.ommc.feature.highlithtWaypoint.HighlightWaypointUtil
	... 32 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at xaero.map.WorldMap.tryLoadLater(WorldMap.java:262)
	at xaero.map.core.XaeroWorldMapCore.onMinecraftRunTick(XaeroWorldMapCore.java:170)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla, fabric, file/Faithful 32x - 1.20.1.zip, file/xekr-redstone-display-1-19-4-加入了经验球显示.zip, file/TraderRemind.zip, file/Noteblock-Utilities-32x.zip, file/FaithfulRedstone_v5.2.zip, file/Door-Utilities-32x.zip, file/醉梦远古残骸RGB.zip, file/思源黑体-中等字体.zip, file/carpetskyadditions-1.20.1-4.4.1-translations.zip, essential
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2413)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60)
	at oolloo.jlw.Wrapper.main(Wrapper.java:53)

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 19.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 444740520 bytes (424 MiB) / 1086324736 bytes (1036 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: RayLink Visual Display Adapter
	Graphics card #0 vendor: Rayvision
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.0.0.8
	Graphics card #1 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2520
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3742
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 72540.41
	Virtual memory used (MB): 20778.54
	Swap memory total (MB): 39936.00
	Swap memory used (MB): 316.69
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx8192m
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.19.4-fabric0.76.0-1.3.1
		appleskin: AppleSkin 2.4.4+mc1.19.4
		architectury: Architectury 8.2.89
		autofish: Autofish 0.9.8-SNAPSHOT
		badpackets: Bad Packets 0.4.2
		beenfo: Beenfo 1.19.3-fabric0.68.1-1.3.3
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		betterpingdisplay: Better Ping Display 1.1.1
		bilibili-danmaku: Bilibili Danmaku 2.1.0-dev
			bilibili-danmaku-1_19_4: Bilibili Danmaku for 1.19.4 2.1.0-dev
				io_netty_netty-codec-http: netty-codec-http 4.1.82.Final
		bsvsb: Better Sodium Video Settings Button 3.0.3
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.66
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.66
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.66
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.66
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.66
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.66
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.66
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.66
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.66
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.66
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.66
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.66
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.66
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.66
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.66
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.66
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.66
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.66
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.66
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.66
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.66
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		capes: Capes 1.5.3+1.19.4
		carpet: Carpet Mod 1.4.101+v230319
		carpet-ams-addition: Carpet AMS Addition 2.6.0
		carpet-extra: Carpet Extra 1.4.100
		carpet-tis-addition: Carpet TIS Addition 1.51.0
			conditional-mixin: conditional mixin 0.4.0
		carpetskyadditions: Carpet Sky Additions 1.19.4-4.3.1
		caxton: Caxton 0.5.0-alpha.5+1.19.4-FABRIC
			com_github_ben-manes_caffeine_caffeine: caffeine 3.1.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-rc.2
			mm: Manningham Mills 2.3
		chat_heads: Chat Heads 0.10.21
		chunkdebug: Chunk Debug 1.0.8
		citresewn: CIT Resewn 1.1.3+1.19.4
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.4
		classic_minecraft_icon: Classic Minecraft Icon 1.1.0
		clientcommands: Client Commands 2.7.13
			betterconfig: BetterConfig 1.0.7
			clientarguments: clientarguments 1.4.3
		cloth-config: Cloth Config v10 10.1.105
			cloth-basic-math: cloth-basic-math 0.6.1
		cmdkeybind: Command Macros 1.6.2-1.19.4
		continuity: Continuity 3.0.0-beta.3+1.19.4
		controlling: Controlling For Fabric 11.1.5
		debugify: Debugify 1.19.4+2.2
		dynamic_fps: Dynamic FPS 3.2.0
		elementa: Elementa 604
		emotecraft: Emotecraft 2.2.7-b.build.50
			bendy-lib: Bendy api 4.0.0
		enhancedblockentities: Enhanced Block Entities 0.9+1.19.4
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 4.2.0+1.19.4
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		essential: Essential 14042+deploy-staging+g1f07116f2
		essential-client: Essential Client 1.3.6
			com_github_senseiwells_arucas: Arucas d1f19ffe01
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		essential-dependencies: Essential Dependencies 0
		exordium: Exordium 1.0.3-mc1.19.4
		explayerenderer: ExtraPlayerRenderer 2.3.1
		fabric-api: Fabric API 0.86.1+1.19.4
			fabric-api-base: Fabric API Base 0.4.28+737a6ee8f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.29+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.9+10ce000ff4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.8+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.38+10ce000ff4
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+0eee1254f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.31+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.10+10ce000ff4
			fabric-commands-v0: Fabric Commands (v0) 0.2.48+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.58+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.14+10ce000ff4
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+6d727b51f4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.17+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.5.1+26f09d40f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.49+10ce000ff4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.17+10ce000ff4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+4b6b93f0f4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.56+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.35+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.21+10ce000ff4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.10+8400c67ef4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.35+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.33+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.19+10ce000ff4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.32+10ce000ff4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.36+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.5+53c11dadf4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.44+10ce000ff4
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+3a1ea2f1f4
			fabric-models-v0: Fabric Models (v0) 0.4.1+a0255436f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.5+10ce000ff4
			fabric-networking-v0: Fabric Networking (v0) 0.3.45+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.1.1+d63b52eaf4
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+86d48884f4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.12+10ce000ff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+95ae8716f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.4.1+a0255436f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+07902599f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.42+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.32+10ce000ff4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.25+10ce000ff4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.45+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.5+10ce000ff4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.3+10ce000ff4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+8400c67ef4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.49+10ce000ff4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.24+10ce000ff4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.11+10ce000ff4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+7bf81db9f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.3.0+1b5f819af4
		fabric-language-kotlin: Fabric Language Kotlin 1.10.10+kotlin.1.9.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
		fabricloader: Fabric Loader 0.14.21
		fabricskyboxes: FabricSkyBoxes 0.7.1+mc1.19.4
		fastchest: FastChest 1.4+1.19.3
		ferritecore: FerriteCore 5.2.0
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		g4mespeed: G4mespeed 1.3.4
		gammautils: Gamma Utils 1.6.15
		gca: GugleCarpetAddition 2.6.0-1.19.4
		ias: In-Game Account Switcher 8.0.2
		imblocker: IMBlockerFabric 1.0.20_pre5
		immediatelyfast: ImmediatelyFast 1.2.5+1.19.4
			net_lenni0451_reflect: Reflect 1.2.1
		indium: Indium 1.0.19+mc1.19.4
		intricarpet: IntriCarpet 2.0.1
		inventoryhud: Inventory HUD + 3.4.12
		inventoryprofilesnext: Inventory Profiles Next 1.10.6
		iris: Iris 1.6.9
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemscroller: Item Scroller craftfix-1.2.7
		java: OpenJDK 64-Bit Server VM 19
		letmeclickandsend: Let Me Click And Send 1.1.0
		libipn: libIPN 3.0.2
		litematica: Litematica 0.14.3
		litematica-server-paster: Litematica Server Paster 1.1.2
		lithium: Lithium 0.11.1
		magiclib: MagicLib 0.7.387+c02a0de-stable
			magiclib-1_19_4: MagicLib for 1.19.4 0.7.387+c02a0de-stable
		malilib: MaLiLib 0.15.4
		masa_gadget_mod: Masa Gadget 3.2.331+61c3583-stable
			masa_gadget_mod-1_19_4: Masa Gadget for 1.19.4 3.2.331+61c3583-stable
		minecraft: Minecraft 1.19.4
		minihud: MiniHUD 0.26.2
		modmenu: Mod Menu 6.3.1
		morecosmetics: MoreCosmetics 1.2
		moreculling: More Culling 1.19.4-0.17.0
		nochatreports: No Chat Reports 1.19.4-v2.1.6
		ommc: Oh My Minecraft Client 0.5.318+ab0c0cf-beta
		org_jetbrains_annotations: annotations 13.0
		pca: Plusls Carpet Addition 0.3.186+ffd08e4-beta
			pca-1_19_4: Plusls Carpet Addition 0.3.186+ffd08e4-beta
		pistorder: Pistorder 1.5.0
		player-animator: Player Animator 1.0.2+1.19.4
		quickshulker: Quick Shulker 1.4.0-1.19.4
			kyrptconfig: Kyrpt Config 1.5.3-1.19.4
			shulkerutils: shulkerutils 1.0.4-1.19
		raknetify: Raknetify (Fabric) 0.1.0+alpha.5.104
		roughlyenoughitems: Roughly Enough Items 11.0.658
			error_notifier: Error Notifier 1.0.9
		roughlyenoughresources: Roughly Enough Resources 2.8.0
		searchables: Searchables 1.0.3
		seedcrackerx: SeedCrackerX 2.14.2
			com_seedfinding_latticg: latticg 1.6
			com_seedfinding_mc_biome: mc_biome b2271807a047bb43ac60c8c20ad47e315f19b9a6
			com_seedfinding_mc_core: mc_core d685a37f0a466d4bf800e7f285daf9ef73c81678
			com_seedfinding_mc_feature: mc_feature c29fd1fcd746e14c1bcdb127da3113ba273db1fd
			com_seedfinding_mc_math: mc_math 0eb505174da8a92550f8ec6efe254e0fa936cc0d
			com_seedfinding_mc_noise: mc_noise a6ab8e6c688491829f8d2adf845392da22ef8e9c
			com_seedfinding_mc_reversal: mc_reversal ca64c0890c106f1a2207623c316fce86f250b918
			com_seedfinding_mc_seed: mc_seed 5518e3ba3ee567fb0b51c15958967f70a6a19e02
			com_seedfinding_mc_terrain: mc_terrain 9e937ddb838e28e79423c287fa18b1ce66f061d7
		skinlayers: 3d Skin Layers 1.5.3-mc1.19.4
		smoothboot: Smooth Boot 1.19.4-1.7.0
		sodium: Sodium 0.4.10+build.24
		sodium-extra: Sodium Extra 0.4.18+mc1.19.4-build.100
			caffeineconfig: CaffeineConfig 1.1.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		syncmatica: Syncmatica 1.18.2-0.3.10
		tweakermore: TweakerMore 3.14.0+build.578
		tweakeroo: Tweakeroo 0.16.0
		tweakerplus: TweakerPlus 1.3.1-SHAPSHOT
		tweakmyclient: Tweak My Client 3.6.409+cc61506-stable
			tweakmyclient-1_19_4: Tweak My Client for 1.19.4 3.6.409+cc61506-stable
		universalcraft: UniversalCraft 289
		viabackwards: ViaBackwards 4.8.0
		viafabric: ViaFabric 0.4.11+45-main
			org_yaml_snakeyaml: snakeyaml 2.2
			viafabric-mc119: ViaFabric for 1.19 0.4.11+45-main
			viaversion: ViaVersion 4.8.0
		vigilance: Vigilance 286
		worldedit: WorldEdit 7.2.14+6360-094b734
		worldeditcui: WorldEditCUI 1.19.4+01
		wthit: wthit 7.6.0
		xaero_map_addition: Xaero Map Addition 0.2.79+91bd337-beta
			xaero_map_addition-1_19_4: Xaero Map Addition for 1.19.4 0.2.79+91bd337-beta
		xaerominimap: Xaero's Minimap 23.8.0
		xaeroworldmap: Xaero's World Map 1.34.1
		yet-another-config-lib: YetAnotherConfigLib 2.4.2
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: 1.19.4-Fabric 0.14.21
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.42, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Faithful 32x - 1.20.1.zip (incompatible), file/xekr-redstone-display-1-19-4-加入了经验球显示.zip, file/TraderRemind.zip (incompatible), file/Noteblock-Utilities-32x.zip (incompatible), file/FaithfulRedstone_v5.2.zip (incompatible), file/Door-Utilities-32x.zip (incompatible), file/醉梦远古残骸RGB.zip (incompatible), file/思源黑体-中等字体.zip (incompatible), file/carpetskyadditions-1.20.1-4.4.1-translations.zip (incompatible)
	Current Language: zh_cn
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics 
```
### Latest CI build tested

- [X] I confirm that this problem still exists with the latest CI build.

**Comment by Hendrix-Shen** [comment]
OMMC 似乎没有正确加载。

**Comment by snpdzk** [comment]
使用最新版ommc仍然崩溃

**Comment by Hendrix-Shen** [comment]
OMMC 是否工作，能否打开其配置菜单？

**Comment by snpdzk** [comment]
无法打开其配置菜单

**Comment by Hendrix-Shen** [comment]
已确认由 OMMC 错误的构建配置引起，请等待 OMMC 仓库 CI 发布构建文件。
